### ISSUE TITLE
Amazon URLs repeatedly endlessly refresh

### ISSUE THREAD

**Issue by hsq-cernansky** [Aaron-P/SmartAmazonSmile#2]
Amazon URLs are redirected to smile.

But if I am not currently logged in, smile.amazon.com URLs just refresh endlessly without every displaying the pages.

Now I know to log in when this happens, but there were weeks where I wondered what the heck was wrong.

Maybe the plugin could notice when this happens and stop the endless page refresh loops.

**Comment by Aaron-P** [comment]
Do you use any other amazon or redirect related addons? This extension
only redirects from www to smile, and only if the authentication cookies
are present. Amazon itself will redirect from smile to www if you aren't
logged in, so that may be one part of what is going on, but unless they
changed how the cookies work or your cookies got corrupted somehow I'm
not sure why this extension would cause this to happen.

**Comment by hsq-cernansky** [comment]
No other Amazon or related add-ons, but who knows what my company's infosec & networking is doing quietly in the background.
It does just look like it is doing what you're saying when I'm not logged in. Amazon.com --> Smile --> back to amazon --> endless loop

**Comment by Aaron-P** [comment]
Can you try clearing your cookies for amazon.com?

**Comment by Aaron-P** [comment]
Is the issue still occurring? Did clearing cookies resolve it?

**Comment by hsq-cernansky** [comment]
Clearing my amazon cookies did work, just tried it. Good to know.

Thanks!

**Comment by Aaron-P** [comment]
Good, so I suspect it was an issue where the cookies were there but the values were invalid for some reason, so amazon thought you weren't logged in but the extension did. I have some code that I think should be able to detect redirect loops, but I'm not quite sure what I want to do about it yet beyond just preventing the redirects the extension does. I'm kind of hesitant to make the extension delete the cookies itself, so I might make it display a message to the user instead or make some kind of option for it.

**Comment by hsq-cernansky** [comment]
Sounds good, thanks for getting me past the issue.
