### ISSUE TITLE
Icon invisible in dark mode

### ISSUE THREAD

**Issue by PhoenixIV** [Aaron-P/SmartAmazonSmile#4]
The only flaw I noticed about you add-on: The icon is completely black with no highlighting borders or background. Therefore it is simply invisible in my dark mode Firefox.

**Comment by Aaron-P** [comment]
This addon doesn't use an icon for anything other than what shows up on the installed extensions page, so unless you're talking about that I'm not really sure what you mean.

**Comment by PhoenixIV** [comment]
Exactly that one :)

It is invisible on dark background.

**Comment by PhoenixIV** [comment]
Feel free to use https://nextcloud.loewenherz.space/index.php/s/m8ppZMyir34fPbs as icon.

I mixed the original design with a little bit more "Amazon". Hope you like it.

Unfortunately Nextcloud is not able to view svg, yet. https://github.com/nextcloud/viewer/issues/959
