### ISSUE TITLE
Available as a userscript (i.e. for Greasemonkey/Tampermonkey/etc)

### ISSUE THREAD

**Issue by e-t-l** [Aaron-P/SmartAmazonSmile#6]
Hi Aaron, is it possible to install this as a simple userscript rather than an extension? Thanks!

**Comment by Aaron-P** [comment]
Not as-is but you could probably do something similar. The basic function of the extension is to check for the existence of a couple of cookies when visiting supported amazon domains and then redirect to the smile equivalent of the domain if they do exist. The extension does it using a blocking webRequest.onBeforeRequest handler to prevent unneeded requests, which as far as I know userscripts can't do, so you would need to do it on page load or something like that.
